### ISSUE TITLE
examples in the spec have wrong tangle fields?

### ISSUE THREAD

**Issue by tschudin** [ssb-ngi-pointer/fusion-identity-spec#7]
great that you push that frontier!

When reading the spec, I stumbled over tangle fields where I was surprised to see the same values popping up. Are these editing errors?

In the ```invite``` op, there is
```
  tangles: {
    fusion: {
      root: '%ZxAJbfRTwhkhpD9viErN9zBzIEzrm6FTndaH/bEnbfI=.sha256', // init
      previous: ['%ZxAJbfRTwhkhpD9viErN9zBzIEzrm6FTndaH/bEnbfI=.sha256']
    }
  }
```

and in the ```consent``` message, the exactly same tangle data appears
```
      previous: ['%ZxAJbfRTwhkhpD9viErN9zBzIEzrm6FTndaH/bEnbfI=.sha256']
```
while I would have expected that its ```previous``` field would point to the ```invite``` message.

The ```proof-of-key``` section has placeholders, it seems:
```
  tangles: {
    fusion: { root, previous }
  }
```

And in the ```tombstone``` operation, the given ```previous``` value is the same as the root
```
tangles: {
    fusion: {
      "root": "%IyaQ/IeV2PYpznyBFCO+qSz3Uu/8HtlqoBbwCE7+dvU=.sha256",
      "previous": [
        "%IyaQ/IeV2PYpznyBFCO+qSz3Uu/8HtlqoBbwCE7+dvU=.sha256"
      ]
    }
  }
```
which would be quite a special case of tombstoning a fusID immediately after having created it (and before sending the DM to self, or having received an invite etc).

Or do I get it wrong and there are reasons for these field values being correct?

**Comment by arj03** [comment]
The examples were bad. I updated them so they show the simplest story of init to tombstone.

Thanks
